spotPython.fun.hyperlight 2024-01-08 10:38:56,332 INFO Starting the logger at level 10 for module spotPython.fun.hyperlight:
spotPython.fun.hyperlight 2024-01-08 10:38:56,374 DEBUG 
config: {'l1': 64, 'epochs': 4096, 'batch_size': 64, 'act_fn': ReLU(), 'optimizer': 'AdamW', 'dropout_prob': 0.07155565167479186, 'lr_mult': 0.6069114944009804, 'patience': 32, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-08 10:38:56,374 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:38:56,375 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-08 10:38:56,375 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-08 10:38:56,375 DEBUG 
config: {'l1': 32, 'epochs': 4096, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adagrad', 'dropout_prob': 0.14524364033873244, 'lr_mult': 3.6307613332962414, 'patience': 256, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-08 10:38:56,375 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:38:56,376 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-08 10:38:56,376 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-08 10:38:56,376 DEBUG 
config: {'l1': 128, 'epochs': 4096, 'batch_size': 8, 'act_fn': ReLU(), 'optimizer': 'Adagrad', 'dropout_prob': 0.1624885330008781, 'lr_mult': 3.995068640608333, 'patience': 256, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-08 10:38:56,376 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:38:56,377 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-08 10:38:56,377 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-08 10:38:56,377 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 8, 'act_fn': ReLU(), 'optimizer': 'Adam', 'dropout_prob': 0.08719071763948699, 'lr_mult': 1.3437019394838083, 'patience': 256, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-08 10:38:56,377 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:42:22,415 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-08 10:42:22,416 DEBUG 
config: {'l1': 32, 'epochs': 8192, 'batch_size': 16, 'act_fn': ReLU(), 'optimizer': 'AdamW', 'dropout_prob': 0.07337419094471936, 'lr_mult': 1.0521300458440637, 'patience': 64, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-08 10:42:22,416 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:42:22,416 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-08 10:42:22,416 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-08 10:42:22,416 DEBUG 
config: {'l1': 64, 'epochs': 4096, 'batch_size': 8, 'act_fn': ReLU(), 'optimizer': 'Adagrad', 'dropout_prob': 0.15316656814635807, 'lr_mult': 2.271853196937431, 'patience': 64, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-08 10:42:22,416 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 DEBUG 
config: {'l1': 64, 'epochs': 8192, 'batch_size': 8, 'act_fn': ReLU(), 'optimizer': 'Adamax', 'dropout_prob': 0.24998473067539212, 'lr_mult': 4.515703902696576, 'patience': 128, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 DEBUG 
config: {'l1': 64, 'epochs': 8192, 'batch_size': 16, 'act_fn': ReLU(), 'optimizer': 'AdamW', 'dropout_prob': 0.21880246359854552, 'lr_mult': 3.4017070711096515, 'patience': 256, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-08 10:42:22,417 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-08 10:42:22,418 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-08 10:42:22,418 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-08 10:42:22,418 DEBUG 
config: {'l1': 64, 'epochs': 4096, 'batch_size': 64, 'act_fn': ReLU(), 'optimizer': 'Adagrad', 'dropout_prob': 0.10145865557914842, 'lr_mult': 2.350820652785106, 'patience': 128, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-08 10:42:22,418 DEBUG fun: Calling train_model
